"""add inn field for User model

Revision ID: a6b2d4b904d3
Revises: dc6b8ead1e3d
Create Date: 2025-02-28 14:48:55.827167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b2d4b904d3'
down_revision: Union[str, None] = 'dc6b8ead1e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('inn', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'inn')
    # ### end Alembic commands ###
