"""Changed user field fio to fullname

Revision ID: a86c0068f570
Revises: dc6b8ead1e3d
Create Date: 2025-02-28 15:10:00.589991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86c0068f570'
down_revision: Union[str, None] = 'dc6b8ead1e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fio', new_column_name='fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fullname', new_column_name='fio')
    # ### end Alembic commands ###
