"""Init

Revision ID: dc6b8ead1e3d
Revises:
Create Date: 2025-02-26 20:07:28.061635

"""

from typing import Sequence, Union

from alembic import op
import fastapi_users
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Session, sessionmaker
from models import Project, User
from fastapi_users.password import PasswordHelper


# revision identifiers, used by Alembic.
revision: str = "dc6b8ead1e3d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("fio", sa.String(length=150), nullable=False),
        sa.Column("email_notify", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    bind = op.get_bind()
    Session = sessionmaker(bind=bind)
    session = Session()
    pwd_helper = PasswordHelper()
    admin_user = session.query(User).filter_by(email="admin@example.com").first()
    if not admin_user:
        # Если администратора нет, создаем его
        new_admin = User(
            email="admin@example.com",
            fio="Иванов Иван Иванович",
            hashed_password=pwd_helper.hash("password"),
            is_superuser=True,
            is_active=True,
            is_verified=True,
        )
        session.add(new_admin)
        session.flush()
        for i in range(1, 101):
            project = Project(
                name=f"Project-{i}", location=f"Moscow", owner_id=new_admin.id
            )
            session.add(project)
    session.commit()
    session.close()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projects")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
